markdown: redcarpet
pygments: false
lsi: false
timezone: Europe/London

authority: http://www.oxfordragball.co.uk

# google:
#   profile_url: https://plus.google.com/113578026960133800736
#   organisation: true
fb: https://www.facebook.com/oxfordragball
twitter:  https://twitter.com/oxfordragball

name: RAG Ball 2013
description:  "On November 23rd, let time stand still as you leave Oxford behind, and come away with to Neverland with RAG Ball 2013!"